### ISSUE TITLE
Exception when starting the app

### ISSUE THREAD

**Issue by IamMusavaRibica** [PolyhedralDev/BiomeToolLegacy#1]
Started with `java -jar BiomeTool-0.2.0-all.jar` from cmd
This is the structure of my folder:
![image](https://user-images.githubusercontent.com/65848142/118864372-35d0e600-b8e0-11eb-91d0-49be0d4d428f.png)
Logs:
```
2403
Searching dir: C:\Users\IamMusavaRibica\OneDrive\Radna površina\coding\TerraPack\BIOMETOOL\.
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassWriter
        at com.dfsek.paralithic.eval.ExpressionBuilder.get(ExpressionBuilder.java:34)
        at com.dfsek.paralithic.eval.parser.Parser.parse(Parser.java:209)
        at com.dfsek.paralithic.eval.parser.Parser.parse(Parser.java:171)
        at com.dfsek.terra.api.math.noise.samplers.noise.ExpressionFunction.<init>(ExpressionFunction.java:30)
        at com.dfsek.terra.config.loaders.config.sampler.templates.noise.ExpressionFunctionTemplate.validate(ExpressionFunctionTemplate.java:61)
        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:211)
        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:250)
        at com.dfsek.terra.config.loaders.config.sampler.NoiseSamplerBuilderLoader.load(NoiseSamplerBuilderLoader.java:29)
        at com.dfsek.terra.config.loaders.config.sampler.NoiseSamplerBuilderLoader.load(NoiseSamplerBuilderLoader.java:16)
        at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:265)
        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:190)
        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:250)
        at com.dfsek.terra.config.loaders.config.sampler.NoiseSamplerBuilderLoader.load(NoiseSamplerBuilderLoader.java:29)
        at com.dfsek.terra.config.loaders.config.sampler.NoiseSamplerBuilderLoader.load(NoiseSamplerBuilderLoader.java:16)
        at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:265)
        at com.dfsek.tectonic.loading.loaders.generic.HashMapLoader.load(HashMapLoader.java:23)
        at com.dfsek.tectonic.loading.loaders.generic.HashMapLoader.load(HashMapLoader.java:12)
        at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:265)
        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:190)
        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:250)
        at com.dfsek.terra.config.loaders.config.sampler.NoiseSamplerBuilderLoader.load(NoiseSamplerBuilderLoader.java:29)
        at com.dfsek.terra.config.loaders.config.sampler.NoiseSamplerBuilderLoader.load(NoiseSamplerBuilderLoader.java:16)
        at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:265)
        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:190)
        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:250)
        at com.dfsek.tectonic.loading.object.ObjectTemplateLoader.load(ObjectTemplateLoader.java:25)
        at com.dfsek.tectonic.loading.ConfigLoader.loadClass(ConfigLoader.java:276)
        at com.dfsek.terra.config.loaders.config.biome.StageBuilderLoader.load(StageBuilderLoader.java:47)
        at com.dfsek.terra.config.loaders.config.biome.StageBuilderLoader.load(StageBuilderLoader.java:19)
        at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:265)
        at com.dfsek.tectonic.loading.loaders.generic.ArrayListLoader.load(ArrayListLoader.java:26)
        at com.dfsek.tectonic.loading.loaders.generic.ArrayListLoader.load(ArrayListLoader.java:16)
        at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:265)
        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:190)
        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:250)
        at com.dfsek.tectonic.loading.object.ObjectTemplateLoader.load(ObjectTemplateLoader.java:25)
        at com.dfsek.tectonic.loading.ConfigLoader.loadClass(ConfigLoader.java:276)
        at com.dfsek.terra.config.loaders.config.biome.BiomeProviderBuilderLoader.load(BiomeProviderBuilderLoader.java:28)
        at com.dfsek.terra.config.loaders.config.biome.BiomeProviderBuilderLoader.load(BiomeProviderBuilderLoader.java:14)
        at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:265)
        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:190)
        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:250)
        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:136)
        at com.dfsek.biome.BiomeTool.getProvider(BiomeTool.java:179)
        at com.dfsek.biome.BiomeTool.main(BiomeTool.java:187)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassWriter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 45 more
```

**Comment by Jobieskii** [comment]
Seems like some libraries are missing as dependencies. Must add:
```
implementation("org.ow2.asm:asm:6.0")
implementation("org.ow2.asm:asm-util:6.0")
```
into dependencies in build.gradle.kts and compile jar

(I don't quite know how to submit it as a pull request.)

**Comment by IamMusavaRibica** [comment]
How do i add it exactly? Do i really have to recompile it

ned, 23. svi 2021. 15:34 Jobieskii ***@***.***> je napisao:
